/* This file is auto-generated by mos build, do not edit! */

#include <stdbool.h>
#include <stdio.h>

#include "common/cs_dbg.h"

#include "mgos_app.h"



#ifndef MGOS_LIB_INFO_VERSION
struct mgos_lib_info {
  const char *name;
  const char *version;
  bool (*init)(void);
};
#endif
#ifndef MGOS_MODULE_INFO_VERSION
struct mgos_module_info {
  const char *name;
  const char *version;
};
#endif

const struct mgos_lib_info mgos_libs_info[] = {

    // "core". deps: [ ]
    {.name = "core", .version = "1.0", .init = NULL},

    // "mylib2". deps: [ "core" ]
    {.name = "mylib2", .version = "2.0", .init = NULL},

    // "mylib1". deps: [ "core" "mylib2" ]
    {.name = "mylib1", .version = "1.0", .init = NULL},

    // Last entry.
    {.name = NULL},
};

const struct mgos_module_info mgos_modules_info[] = {

    {.name = "mongoose-os", .version = "xxx"},

    // Last entry.
    {.name = NULL},
};

bool mgos_deps_init(void) {
  for (const struct mgos_lib_info *l = mgos_libs_info; l->name != NULL; l++) {
    LOG(LL_DEBUG, ("Init %s %s...", l->name, l->version));
    if (l->init != NULL && !l->init()) {
      LOG(LL_ERROR, ("%s init failed", l->name));
      return false;
    }
  }
  for (const struct mgos_module_info *m = mgos_modules_info; m->name != NULL; m++) {
    LOG(LL_DEBUG, ("Module %s %s", m->name, m->version));
  }
  return true;
}
