- name: copy mos binaries ({{ mos_version_tag }})
  tags: mos
  synchronize:
    src: ../../mos/downloads/mos/
    dest: /data/downloads/mos-{{ mos_version_tag }}

- name: create symlink mos to mos-latest
  tags: mos
  when: mos_version_tag == "latest"
  file:
    src: /data/downloads/mos-latest
    dest: /data/downloads/mos
    state: link

- name: create symlink mos-release to mos-{{ mos_version_tag }}
  tags: mos
  when: mos_version_tag != "latest"
  file:
    src: /data/downloads/mos-{{ mos_version_tag }}
    dest: /data/downloads/mos-release
    state: link
