# Build, push and pull "fwbuild-instance" and "cloud-mos" images. The caller
# should typically set the "cur_mos_version_tag" variable when including this
# file.
#
# Maybe in the future these two images will be merged into a single one, so for
# now they are at least grouped in this single yaml.

- name: build cloud-mos:{{ cur_mos_version_tag }}
  tags: cloud-mos
  when: build == "yes"
  local_action: shell make -C ../docker/cloud-mos docker-build docker-tag docker-push TAG={{ cur_mos_version_tag }}

- name: build fwbuild-instance:{{ cur_mos_version_tag }}
  tags: fwbuild-instance
  when: build == "yes"
  local_action: shell make -C ../docker/fwbuild-instance docker-build docker-tag docker-push TAG={{ cur_mos_version_tag }}

- name: Pull cloud-mos image:{{ cur_mos_version_tag }}
  tags:
    - cloud-mos
  shell: >-
    docker pull docker.io/mgos/mos:{{ cur_mos_version_tag }}

- name: Pull fwbuild-instance image:{{ cur_mos_version_tag }}
  tags:
    - fwbuild-instance
  shell: >-
    docker pull docker.io/mgos/fwbuild-instance:{{ cur_mos_version_tag }}
