- name: build fwbuild-manager:{{ fwbuild_manager_tag }}
  tags: fwbuild-manager
  when: build == "yes"
  local_action: shell make -C ../docker/fwbuild-manager docker-build docker-tag docker-push TAG={{ fwbuild_manager_tag }}

- name: Pull fwbuild-manager image:{{ fwbuild_manager_tag }}
  tags:
    - fwbuild-manager
  shell: >-
    docker pull docker.io/mgos/fwbuild-manager:{{ fwbuild_manager_tag }}

- name: install fwbuild-manager docker job
  tags: fwbuild-manager
  docker_container:
    image: docker.io/mgos/fwbuild-manager:{{ fwbuild_manager_tag }}
    name: fwbuild-manager
    ports:
      - 443:443
      - 80:80
    expose:
      - 443
      - 80
    command: >-
      --logtostderr --v=2
      --volumes-dir={{ fwbuild_volumes_dir }}
      --port=80
      --port-tls=443
      --cert-file=/data/letsencrypt/live/mongoose.cloud/fullchain.pem
      --key-file=/data/letsencrypt/live/mongoose.cloud/privkey.pem

    volumes:
      - "{{ fwbuild_volumes_dir }}:{{ fwbuild_volumes_dir }}"
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/letsencrypt:/data/letsencrypt:ro
    state: started
    pull: yes
    restart_policy: always
