//
// Copyright (c) 2014-2019 Cesanta Software Limited
// All rights reserved
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by "stringer -type=transport transport.go"; DO NOT EDIT

package mgrpc

import "fmt"

const _transport_name = "tHTTP_POSTtWebSockettPlainTCPtSerialtMQTTtAzureDMtGCPtWatson"

var _transport_index = [...]uint8{0, 10, 20, 29, 36, 41, 49, 53, 60}

func (i transport) String() string {
	if i < 0 || i >= transport(len(_transport_index)-1) {
		return fmt.Sprintf("transport(%d)", i)
	}
	return _transport_name[_transport_index[i]:_transport_index[i+1]]
}
